server:
  port: 8082

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
    url: jdbc:postgresql://172.17.0.2:5432/postgres
    username: postgres
    password: 1234